### ISSUE TITLE
Generate inner enum classes

### ISSUE THREAD

**Issue by Chrimle** [Chrimle/openapi-to-java-records-mustache-templates#5]
Whenever a `{property}.type` is `enum`, the generated object should have an inner enum class generated also.

**Comment by ycaroff** [comment]
For what it's worth, if {property}.type is <type>, and {property}.enum=[ ...values... ], you can create an inner enum by appending this code to pojo.mustache just before the final closing curly bracket:

{{#vars}}{{#isEnum}}
  public enum {{datatypeWithEnum}} {
  	{{#allowableValues}}
  	{{#enumVars}}
  	{{{name}}}({{{value}}}){{^-last}},{{/-last}}{{#-last}};{{/-last}}
  	{{/enumVars}}
  	{{/allowableValues}}

	private {{{dataType}}} {{{name}}};

	{{datatypeWithEnum}}({{{dataType}}} {{{name}}}) {
		this.{{{name}}} = {{{name}}};
	}
  }
{{/isEnum}}{{/vars}}

I needed that feature so I added it to your template, so if other users also need it, feel free to integrate/adapt it to your needs. By the way, thanks a lot for your work !

Yann

**Comment by Chrimle** [comment]
Hi @ycaroff !

Thank you for this suggestion! :heart: 

This does indeed solve this issue - I will work on adding this functionality right away!
One tweak that will be needed, is to support the configOption [`useEnumCaseInsensitive`](https://github.com/Chrimle/openapi-to-java-records-mustache-templates/wiki/Supported-%27openapi‐generator‐maven‐plugin%27-Configuration-options#supported-configoptions-options) for these inner enums as well. Furthermore, `enum` classes should have `String value` fields regardless when generated as a class or an inner class. #181 

Thank you for your kind words - I do really appreciate it! :heart:

**Comment by Chrimle** [comment]
How odd... `{{{datatypeWithEnum}}}` will append `Enum` to the end of the enum class name. However, `{{{datatype}}}` is `String`. This means that all inner enums will be suffixed by `Enum`... 

Maybe that is okay since it is the default behaviour of `openapi-generator-maven-plugin`, but not great in terms of customization - there are `configOption`s for model prefixes/suffixes already...

**Comment by Chrimle** [comment]
@ycaroff inner `enum` classes can now be generated, by using [Version 1.10.0](https://github.com/Chrimle/openapi-to-java-records-mustache-templates/releases/tag/v1.10.0)!
 It has some additional features, but also limitations (compared to standalone enum classes).

There are more potential improvements related to enums planned: #188 and #182
